/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    "Overview",
    {
      type: "html",
      value: "Vital API", // The HTML to be rendered
      className: "sidebar-first-html-title",
    },
    {
      type: "category",
      label: "User",
      items: [
        {
          type: "autogenerated",
          dirName: "user", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Create User",
          href: "/api-reference/user#create-user", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Get User",
          href: "/api-reference/user#get-user", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Delete User",
          href: "/api-reference/user#delete-user", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Get all Users",
          href: "/api-reference/user#get-all-users-for-team", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Get Connected Providers",
          href: "/api-reference/user#get-users-connected-providers", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Refresh User Data",
          href: "/api-reference/user#refresh-users-data", // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
    {
      type: "category",
      label: "Providers",
      items: [
        {
          type: "autogenerated",
          dirName: "providers", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "List of Providers",
          href: "/api-reference/providers#list-of-supported-providers", // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
    {
      type: "category",
      label: "Link",
      items: [
        {
          type: "autogenerated",
          dirName: "link", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Create a new link token",
          href: "/api-reference/link#create-a-new-link-token", // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
    {
      type: "html",
      value: "Data", // The HTML to be rendered
      className: "sidebar-first-html-title",
    },
    {
      type: "category",
      label: "Sleep",
      items: [
        {
          type: "autogenerated",
          dirName: "data/sleep", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Summary",
          href: "/api-reference/data/sleep#summary", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Stream",
          href: "/api-reference/data/sleep#stream", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Raw",
          href: "/api-reference/data/sleep#raw", // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },

    {
      type: "category",
      label: "Workouts",
      items: [
        {
          type: "autogenerated",
          dirName: "data/workouts", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Summary",
          href: "/api-reference/data/workouts#summary", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Stream",
          href: "/api-reference/data/workouts#stream", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Raw",
          href: "/api-reference/data/workouts#raw", // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
    {
      type: "category",
      label: "Profile",
      items: [
        {
          type: "autogenerated",
          dirName: "data/profile", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Summary",
          href: "/api-reference/data/profile#summary", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Raw",
          href: "/api-reference/data/profile#raw", // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
    {
      type: "category",
      label: "Activity",
      items: [
        {
          type: "autogenerated",
          dirName: "data/activity", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Summary",
          href: "/api-reference/data/activity#summary", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Raw",
          href: "/api-reference/data/activity#raw", // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
    {
      type: "category",
      label: "Body",
      items: [
        {
          type: "autogenerated",
          dirName: "data/body", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Summary",
          href: "/api-reference/data/body#summary", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Raw",
          href: "/api-reference/data/body#raw", // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
    {
      type: "category",
      label: "Vitals",
      items: [
        {
          type: "autogenerated",
          dirName: "data/vitals", // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
    {
      type: "html",
      value: "Labs", // The HTML to be rendered
      className: "sidebar-html-title",
    },
    {
      type: "category",
      label: "Testkits",
      items: [
        {
          type: "autogenerated",
          dirName: "labs/testkits", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Get Testkits",
          href: "/api-reference/labs/testkits/#get-testkits", // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
    {
      type: "category",
      label: "Orders",
      items: [
        {
          type: "autogenerated",
          dirName: "labs/orders", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Create Order",
          href: "/api-reference/labs/orders/#create-orders", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Cancel Order",
          href: "/api-reference/labs/orders/#cancel-order", // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
    {
      type: "category",
      label: "Results",
      items: [
        {
          type: "autogenerated",
          dirName: "labs/results", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Get Results",
          href: "/api-reference/labs/results/#get-results", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Get Results Raw",
          href: "/api-reference/labs/results/#get-results-raw", // Generate sidebar slice from docs/tutorials/easy
        },
        {
          type: "link",
          label: "Get Results Metadata",
          href: "/api-reference/labs/results/#get-result-metadata", // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
  ],
};

module.exports = sidebars;
