/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    {
      type: "html",
      value: "Vital API", // The HTML to be rendered
      className: "sidebar-first-html-title",
    },
    {
      type: "category",
      label: "User",
      items: [
        {
          type: "autogenerated",
          dirName: "user",
        },
        {
          type: "link",
          label: "Create User",
          href: "/api-reference/user#create-user",
        },
        {
          type: "link",
          label: "Get User",
          href: "/api-reference/user#get-user",
        },
        {
          type: "link",
          label: "Delete User",
          href: "/api-reference/user#delete-user",
        },
        {
          type: "link",
          label: "Get all Users",
          href: "/api-reference/user#get-all-users-for-team",
        },
        {
          type: "link",
          label: "Get Connected Providers",
          href: "/api-reference/user#get-users-connected-providers",
        },
        {
          type: "link",
          label: "Refresh User Data",
          href: "/api-reference/user#refresh-users-data",
        },
        {
          type: "link",
          label: "Deregister a provider",
          href: "/api-reference/user#deregister-provider-for-user",
        },
      ],
    },
    {
      type: "category",
      label: "Providers",
      items: [
        {
          type: "autogenerated",
          dirName: "providers",
        },
        {
          type: "link",
          label: "List of Providers",
          href: "/api-reference/providers#list-of-supported-providers",
        },
      ],
    },
    {
      type: "category",
      label: "Link",
      items: [
        {
          type: "autogenerated",
          dirName: "link",
        },
        {
          type: "link",
          label: "Generate a link token",
          href: "/api-reference/link#generate-link-token",
        },
        {
          type: "link",
          label: "Link OAuth provider",
          href: "/api-reference/link#link-oauth-provider",
        },
        {
          type: "link",
          label: "Link Password provider",
          href: "/api-reference/link#link-password-provider",
        },
        {
          type: "link",
          label: "Link Email provider",
          href: "/api-reference/link#link-email-provider",
        },
      ],
    },
    {
      type: "html",
      value: "Data", // The HTML to be rendered
      className: "sidebar-first-html-title",
    },
    {
      type: "category",
      label: "Sleep",
      items: [
        {
          type: "autogenerated",
          dirName: "data/sleep",
        },
        {
          type: "link",
          label: "Summary",
          href: "/api-reference/data/sleep#summary",
        },
        {
          type: "link",
          label: "Stream",
          href: "/api-reference/data/sleep#stream",
        },
        {
          type: "link",
          label: "Raw",
          href: "/api-reference/data/sleep#raw",
        },
      ],
    },

    {
      type: "category",
      label: "Workouts",
      items: [
        {
          type: "autogenerated",
          dirName: "data/workouts",
        },
        {
          type: "link",
          label: "Summary",
          href: "/api-reference/data/workouts#summary",
        },
        {
          type: "link",
          label: "Stream",
          href: "/api-reference/data/workouts#stream",
        },
        {
          type: "link",
          label: "Raw",
          href: "/api-reference/data/workouts#raw",
        },
      ],
    },
    {
      type: "category",
      label: "Profile",
      items: [
        {
          type: "autogenerated",
          dirName: "data/profile",
        },
        {
          type: "link",
          label: "Summary",
          href: "/api-reference/data/profile#summary",
        },
        {
          type: "link",
          label: "Raw",
          href: "/api-reference/data/profile#raw",
        },
      ],
    },
    {
      type: "category",
      label: "Activity",
      items: [
        {
          type: "autogenerated",
          dirName: "data/activity",
        },
        {
          type: "link",
          label: "Summary",
          href: "/api-reference/data/activity#summary",
        },
        {
          type: "link",
          label: "Raw",
          href: "/api-reference/data/activity#raw",
        },
      ],
    },
    {
      type: "category",
      label: "Body",
      items: [
        {
          type: "autogenerated",
          dirName: "data/body",
        },
        {
          type: "link",
          label: "Summary",
          href: "/api-reference/data/body#summary",
        },
        {
          type: "link",
          label: "Raw",
          href: "/api-reference/data/body#raw",
        },
      ],
    },
    {
      type: "category",
      label: "Vitals",
      items: [
        {
          type: "autogenerated",
          dirName: "data/vitals",
        },
      ],
    },
    {
      type: "html",
      value: "Lab Testing", // The HTML to be rendered
      className: "sidebar-html-title",
    },
    {
      type: "category",
      label: "Orders",
      items: [
        {
          type: "autogenerated",
          dirName: "labsv2/orders",
        },
        {
          type: "link",
          label: "Create Order",
          href: "/api-reference/labsv2/orders/#create-order",
        },
        {
          type: "link",
          label: "Get Order",
          href: "/api-reference/labsv2/orders/#get-order",
        },
        {
          type: "link",
          label: "Cancel Order",
          href: "/api-reference/labsv2/orders/#cancel-order",
        },
      ],
    },
    {
      type: "category",
      label: "Lab Tests",
      items: [
        {
          type: "autogenerated",
          dirName: "labsv2/lab_tests",
        },
        {
          type: "link",
          label: "Get Available Tests",
          href: "/api-reference/labsv2/lab_tests/#result",
        },
      ],
    },
    {
      type: "category",
      label: "Results",
      items: [
        {
          type: "autogenerated",
          dirName: "labsv2/results",
        },
        {
          type: "link",
          label: "Get Results",
          href: "/api-reference/labsv2/results/#result",
        },
        {
          type: "link",
          label: "Get Results PDF",
          href: "/api-reference/labsv2/results/#result-pdf",
        },
        {
          type: "link",
          label: "Get Results Metadata",
          href: "/api-reference/labsv2/results/#result-metadata",
        },
      ],
    },
    {
      type: "html",
      value: "Legacy", // The HTML to be rendered
      className: "sidebar-html-title",
    },
    {
      type: "category",
      label: "Testkits",
      items: [
        {
          type: "autogenerated",
          dirName: "labs/testkits",
        },
        {
          type: "link",
          label: "Get Testkits",
          href: "/api-reference/labs/testkits/#get-testkits",
        },
      ],
    },
    {
      type: "category",
      label: "Orders",
      items: [
        {
          type: "autogenerated",
          dirName: "labs/orders",
        },
        {
          type: "link",
          label: "Create Order",
          href: "/api-reference/labs/orders/#create-orders",
        },
        {
          type: "link",
          label: "Cancel Order",
          href: "/api-reference/labs/orders/#cancel-order",
        },
      ],
    },
    {
      type: "category",
      label: "Results",
      items: [
        {
          type: "autogenerated",
          dirName: "labs/results",
        },
        {
          type: "link",
          label: "Get Results",
          href: "/api-reference/labs/results/#get-results",
        },
        {
          type: "link",
          label: "Get Results Raw",
          href: "/api-reference/labs/results/#get-results-raw",
        },
        {
          type: "link",
          label: "Get Results Metadata",
          href: "/api-reference/labs/results/#get-result-metadata",
        },
      ],
    },
  ],
};

module.exports = sidebars;
