/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    {
      type: "html",
      value: "Lab Testing", // The HTML to be rendered
      className: "sidebar-first-html-title",
    },
    {
      type: "category",
      label: "Order Process",
      items: [
        {
          type: "autogenerated",
          dirName: "process",
        },
        {
          type: "link",
          label: "Lab testing Process",
          href: "/lab-testing/process/#introduction",
        },
        {
          type: "link",
          label: "Testing Modalities",
          href: "/lab-testing/process/#modalities",
        },
      ],
    },
    {
      type: "category",
      label: "Results",
      items: [
        {
          type: "autogenerated",
          dirName: "process",
        },
        {
          type: "link",
          label: "Lab testing Process",
          href: "/lab-testing/results/#introduction",
        },
        {
          type: "link",
          label: "Testing Modalities",
          href: "/lab-testing/results/#modalities",
        },
      ],
    },
    {
      type: "category",
      label: "Workflow",
      items: [
        {
          type: "autogenerated",
          dirName: "process",
        },
        {
          type: "link",
          label: "Lab testing Process",
          href: "/lab-testing/workflows/#introduction",
        },
        {
          type: "link",
          label: "Testing Modalities",
          href: "/lab-testing/workflows/#modalities",
        },
      ],
    },
  ],
};

module.exports = sidebars;
