# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # triggered on a custom event
  repository_dispatch:
    types: [trigger_ci]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Download swagger and push it
        run: |
          echo "$GITHUB_WORKSPACE"
          wget https://api.us.junction.com/openapi.json -O ./docs/swagger.json
          wget https://api.management.junction.com/openapi.json -O ./docs/org-management-api.json
          git config user.name Vital
          git config user.email developers@tryvital.io
          git add .
          git commit -m "[automated commit] update swagger.json"
          git push

